
import "./globals.css";
import {Outfit} from "next/font/google";

const inter = Outfit({subsets:["latin"]})

export const metadata = {
  title: "Meet-Point",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}>
        {children}
      </body>
    </html>
  );
}
